### ISSUE TITLE
seems the current implementation is for regression, not binary classification?

### ISSUE THREAD

**Issue by kochat** [Xtra-Computing/SimFL#1]
the calculation of g, h seems like using mse loss, not log loss?

void InsStat::updateGH() {
    sum_gh = GHPair(0, 0);
    GHPair *gh_pair_data = gh_pair.host_data();
    int *nid_data = nid.host_data();
    float_type *stats_y_data = y.host_data();
    float_type *stats_yp_data = y_predict.host_data();
    LOG(DEBUG) << y_predict;
    LOG(TRACE) << "initializing instance statistics";
    //TODO parallel?
    for (int i = 0; i < n_instances; ++i) {
        nid_data[i] = 0;
        //TODO support other objective function
        gh_pair_data[i].g = stats_yp_data[i] - stats_y_data[i];
        gh_pair_data[i].h = 1;
        sum_gh = sum_gh + gh_pair_data[i];
    }
}

**Comment by QinbinLi** [comment]
Hi @kochat ,

We take the binary classification as a regression problem. If the predicted value is larger than 0.5, then the predicted class is 1, otherwise is 0.
